name: CI
on:
 - push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby_image:
          - ruby:3.0
          - ruby:2.7
          - ruby:2.6
    container:
      image: ${{ matrix.ruby_image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and run tests
        run: |
          bundle
          rake spec
