name: Verify
on:
 - push

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    container:
      image: ruby
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and run tests
        run: |
          bundle
          rake spec
